---
# Playbook para configuración de los 2 servidores del proyecto
- name: Aprovisionar Servidor Frontend (Nginx)
  hosts: front
  become: true
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

- name: Aprovisionar Servidor Backend (FastAPI y SQLite)
  hosts: back
  become: true
  tasks:
    - name: Instalar Python y SQLite
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - sqlite3
        state: present
        update_cache: yes

    - name: Instalar dependencias del Backend
      pip:
        requirements: /vagrant/requirements.txt
        extra_args: --break-system-packages
